<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2chnq0u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2chnq0u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2chnq0u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2chnq0u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2chnq0u\appDevDebugProjectContainer([
    'container.build_hash' => '2chnq0u',
    'container.build_id' => 'dbc0fce8',
    'container.build_time' => 1586381358,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2chnq0u');
