<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_message.spam_detector' shared service.

include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\message-bundle\\SpamDetection\\SpamDetectorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\message-bundle\\SpamDetection\\NoopSpamDetector.php';

return $this->services['fos_message.spam_detector'] = new \FOS\MessageBundle\SpamDetection\NoopSpamDetector();
