<?php

namespace Proxies\__CG__\Utilisateurs\UtilisateursBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partenaire extends \Utilisateurs\UtilisateursBundle\Entity\Partenaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'id', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'nom', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'prenom', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'mail', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'mdp', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'tel', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'taxi', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'nb'];
        }

        return ['__isInitialized__', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'id', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'nom', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'prenom', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'mail', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'mdp', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'tel', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'taxi', '' . "\0" . 'Utilisateurs\\UtilisateursBundle\\Entity\\Partenaire' . "\0" . 'nb'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Partenaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdp($mdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdp', [$mdp]);

        return parent::setMdp($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', []);

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeTaxi(\Utilisateurs\UtilisateursBundle\Entity\Taxi $matriculeTaxi = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeTaxi', [$matriculeTaxi]);

        return parent::setMatriculeTaxi($matriculeTaxi);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxi(\Utilisateurs\UtilisateursBundle\Entity\Taxi $taxi = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxi', [$taxi]);

        return parent::setTaxi($taxi);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxi', []);

        return parent::getTaxi();
    }

    /**
     * {@inheritDoc}
     */
    public function setNb($nb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNb', [$nb]);

        return parent::setNb($nb);
    }

    /**
     * {@inheritDoc}
     */
    public function getNb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNb', []);

        return parent::getNb();
    }

}
