<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

/**
 * InventaireCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireCRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInventaire($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT i FROM UtilisateursUtilisateursBundle:InventaireC i 
WHERE i.partenaire=$id AND EXTRACT(MONTH FROM i.date_i)=EXTRACT(MONTH FROM CURRENT_DATE() )");
        return $query->getResult();
    }
}
