<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

/**
 * InventaireRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireRRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInventaireR($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT i FROM UtilisateursUtilisateursBundle:InventaireR i 
WHERE i.partenaire=$id");
        return $query->getResult();
    }
}
