<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

/**
 * TaxiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxiRepository extends \Doctrine\ORM\EntityRepository
{
}
