<?php

namespace FeedBackBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function isRating($client , $part){
        $Query=$this->getEntityManager()->createQuery(
            "select A from FeedBackBundle:Rating A where A.client=:client and A.part=:part"
        )
            ->setParameter('part',$part)
            ->setParameter('client',$client);
        return $Query->getResult();
    }
}
