<?php

namespace FeedBackBundle\Repository;

/**
 * ReclammationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclammationsRepository extends \Doctrine\ORM\EntityRepository
{
}
