<?php

namespace FeedBackBundle\Repository;

/**
 * ReponseReclammationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseReclammationRepository extends \Doctrine\ORM\EntityRepository
{
}
