<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT7q4xag\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT7q4xag/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT7q4xag.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT7q4xag\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT7q4xag\appProdProjectContainer([
    'container.build_hash' => 'T7q4xag',
    'container.build_id' => '3a7526da',
    'container.build_time' => 1580766957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT7q4xag');
